@startuml
title 販売管理サガ

|受注コンテキスト|
start
:注文を登録する;

|在庫コンテキスト|
:在庫を引当する;

|受注コンテキスト|
:出荷指示をする;

|出荷コンテキスト|
:商品をピッキングする;
:商品を出荷する;

|配送コンテキスト|
:商品を集荷する;
:追跡番号を発行する;

|受注コンテキスト|
:出荷案内を出す;

|決済コンテキスト|
:注文決済する;

|配送コンテキスト|
:商品を配達する;

|受注コンテキスト|
:入金を確認する;

stop
@enduml
