@startuml
title 境界づけられたコンテキスト内の集約／エンティティオブジェクト／値オブジェクト 

package "Eコマース事業" {
    [販売管理] as SalesManagement
}

package 受注コンテキスト {
    package "受注" {
        [受注<<集約>>]
        [受注明細<<エンティティオブジェクト>>]
        [数量<<値オブジェクト>>]
    }
}


"Eコマース事業" --> "受注"
"受注<<集約>>" --> "受注明細<<エンティティオブジェクト>>"
"受注明細<<エンティティオブジェクト>>" --> "数量<<値オブジェクト>>"
@enduml
