@startuml
title 境界づけられたコンテキスト内のドメインルール

package "Eコマース事業" {
    [販売管理] as SalesManagement
}

package 受注コンテキスト {
    package "受注" {
        [受注<<集約>>]
        [受注明細<<エンティティオブジェクト>>]
        [注文内容チェック<<ドメインルール>>]
    }
}


"Eコマース事業" --> "受注"
"受注<<集約>>" --> "受注明細<<エンティティオブジェクト>>"
"受注<<集約>>" --> "注文内容チェック<<ドメインルール>>"
"受注明細<<エンティティオブジェクト>>" -> "注文内容チェック<<ドメインルール>>"
@enduml
