title 境界づけられたコンテキス内のコマンド/クエリ

package "Eコマース事業" {
    [販売管理] as SalesManagement
}

package 受注コンテキスト {
    package "受注" {
      package コマンド {
          [受注登録]
          [受注更新]
          [受注キャンセル]
      }
      package クエリ {
          [受注照会] 
          [受注一覧照会]
      }
    }
}


"Eコマース事業" --> "受注"
